Repository YAPP-Github/24th-Web-Team-3-FE, pull requests merged in 2024-06, with the labels that each got.

#2 ✨ Feat | 프로젝트 패키지 초기화
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  README.md
  components.json
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/pwa-icons/192.png
  public/pwa-icons/512.png
  public/sw.js
  public/workbox-e9849328.js
  src/app/globals.css
  src/app/layout.tsx
  src/app/manifest.ts
  src/app/page.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/utils/cn.ts
  src/utils/index.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feat

#10 setting: pwa 환경 세팅
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/sw.js
  public/workbox-3c9d0171.js
  public/workbox-e9849328.js
  src/app/manifest.json
  src/app/manifest.ts
Labels: ⚙️ setting

#8 Setting/디자인 시스템 토큰 정의
  components.json
  src/app/layout.tsx
  src/font/PretendardVariable.woff2
  src/styles/globals.css
  src/styles/main.css
  tailwind.config.ts
Labels: ⚙️ setting

#14 Setting/design-system 변경사항 반영
  tailwind.config.ts
Labels: ⚙️ setting

#17 [issues/16] Setting/custom fetch
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/_components/QueryProviders.tsx
  src/app/api/customFetch.ts
  src/app/api/index.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/common/ErrorBoundary.tsx
  src/common/ErrorHandlingWrapper.tsx
  src/common/Test.tsx
  src/components/Test.tsx
Labels: ✨ Feat, ⚙️ setting

#18 [issues/6] Feat/icon component
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/assets/solar-icons/basketballBold.svg
  src/assets/solar-icons/buildingsBold.svg
  src/assets/solar-icons/emojiFunnyCircleBold.svg
  src/assets/solar-icons/fireBold.svg
  src/assets/solar-icons/heartAngleBold.svg
  src/assets/solar-icons/starFallMinimalisticBold.svg
  src/components/Icon.tsx
  src/components/index.ts
  src/types/index.ts
  tailwind.config.ts
Labels: ✨ Feat

#22 Feat/ Badge 컴포넌트 구현 및 twmerge 커스터마이징
  src/components/Badge.tsx
  src/components/Icon.tsx
  src/components/index.ts
  src/utils/cn.ts
  tailwind.config.ts
Labels: ✨ Feat
